# Generated by Django 4.2 on 2023-04-09 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='categoria_preferida',
        ),
        migrations.AddField(
            model_name='sneaker',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.categoria'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='imagem',
            field=models.ImageField(upload_to='store/images/'),
        ),
    ]
