# Generated by Django 4.2 on 2023-04-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_sneaker_categoria_preferida_sneaker_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='marca_preferida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.marca'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(upload_to='store/images/utilizadores/'),
        ),
        migrations.DeleteModel(
            name='PreferenciaMarca',
        ),
    ]
