# Generated by Django 4.2 on 2023-05-02 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cliente_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cliente')),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sneaker')),
            ],
        ),
    ]
