# Generated by Django 4.2 on 2023-05-08 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_carrinho_data_inatividade_alter_sneaker_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='data_inatividade',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 19, 40, 26, 388964)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(blank=True, default='store/images/default_profile_pic.png', null=True, upload_to='clientes/'),
        ),
    ]
