# Generated by Django 4.2 on 2023-05-09 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_carrinho_data_inatividade_alter_cliente_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='data_inatividade',
            field=models.DateField(default=datetime.datetime(2023, 5, 16, 16, 12, 22, 597097)),
        ),
    ]
