# Generated by Django 4.2 on 2023-05-09 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_carrinho_data_inatividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='data_inatividade',
            field=models.DateField(default=datetime.datetime(2023, 5, 16, 16, 47, 17, 350216)),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='status',
            field=models.CharField(choices=[('processamento', 'Em Processamento'), ('cancelada', 'Cancelada'), ('entregue', 'Entregue')], max_length=255),
        ),
    ]
