# Generated by Django 4.2.1 on 2023-05-09 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_carrinho_data_inatividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregadoloja',
            name='imagem',
            field=models.ImageField(default='store/images/default_profile_pic.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='data_inatividade',
            field=models.DateField(default=datetime.datetime(2023, 5, 16, 23, 11, 31, 926035)),
        ),
    ]
